name: Benchmark+Test PR
on:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash --noprofile --norc -CeEuxo pipefail {0}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 8

    steps:
      - uses: actions/checkout@v4
      - name: determine the new added project
        id: determine_project
        run: |
          # Get the name of the main branch (assuming it's 'main')
          MAIN_BRANCH="main"

          # Fetch the main branch
          git fetch origin $MAIN_BRANCH:$MAIN_BRANCH

          NEW_FOLDER=$(git diff --name-status $MAIN_BRANCH | grep -E '^[AM]' | awk '{print $2}' | grep 'Cargo.toml' | awk -F/ '{printf("%s/%s\n", $1, $2)}' | uniq)

          # Extract the names of new folders
          if [[ -z "$NEW_FOLDER" ]]; then
            echo "No new project found - skipping the build"
            gh run cancel ${{ github.run_id }}
            gh run watch ${{ github.run_id }}
          fi

          # Set the output variable
          echo "PROJECT_FOLDER=$NEW_FOLDER" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: build
        run: cargo build --release
        working-directory: ${{ steps.determine_project.outputs.PROJECT_FOLDER }}

      - name: test
        run: cargo run --release -- ../../samples/weather_100.csv > X
        working-directory: ${{ steps.determine_project.outputs.PROJECT_FOLDER }}

      - name: diff results
        run: |
          # Check if the results are correct
          diff -w X ../../samples/expected/weather_100.txt

        working-directory: ${{ steps.determine_project.outputs.PROJECT_FOLDER }}
